[[main]]
  name = "document"
  url = "/docs/"
  identifier = "docs"
  weight = 10

[[main]]
  name = "blog"
  url = "/blog/"
  identifier = "blog"
  weight = 30

[[main]]
  name = "community"
  url = "/community/"
  identifier = "community"
  weight = 40
